### ISSUE TITLE
Update docs or remove parameter from EClientSocket.reqHistoricalData

### ISSUE THREAD

**Issue by benmccann** [InteractiveBrokers/tws-api-public#3]
The [reqHistoricalData API docs](https://www.interactivebrokers.com/en/software/api/apiguide/java/reqhistoricaldata.htm) say `chartOptions` is for internal use only. In that case, why is it exposed in the API? Should that parameter be removed or the docs updated?

**Comment by ksmaguineib** [comment]
This issues list is not being watched, please use https://github.com/InteractiveBrokers/tws-api/issues
